# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - docs-on-readthedocs
    vars:
      rtd_webhook_id: '38576'
      rtd_project_name: 'airship-shipyard'
      ensure_global_symlinks: true
    check:
      jobs:
        - openstack-tox-py312
        - airship-shipyard-openstack-tox-pep8-noble
        - airship-shipyard-openstack-tox-cover-noble
        - airship-shipyard-chart-build-gate
        - airship-shipyard-chart-build-latest-htk
        - airship-airflow-dependency-vulnerability-check
        - airship-shipyard-dependency-vulnerability-check
        - airship-shipyard-whitespace-lint-gate
        - airship-shipyard-image-gate-ubuntu_noble
        - shipyard-airskiff-deployment-noble-kubeadm
    gate:
      jobs:
        - openstack-tox-py312
        - airship-shipyard-openstack-tox-pep8-noble
        - airship-shipyard-openstack-tox-cover-noble
        - airship-shipyard-chart-build-gate
        - airship-shipyard-whitespace-lint-gate
        - airship-shipyard-image-gate-ubuntu_noble

    post:
      jobs:
        - airship-shipyard-docker-build-publish-ubuntu_noble
        - shipyard-upload-git-mirror

- nodeset:
    name: airship-shipyard-single-node
    nodes:
      - name: primary
        label: ubuntu-bionic

- nodeset:
    name: airship-shipyard-single-node-jammy
    nodes:
      - name: primary
        label: ubuntu-jammy

- nodeset:
    name: airship-shipyard-single-node-noble
    nodes:
      - name: primary
        label: ubuntu-noble

- job:
    name: airship-airflow-dependency-vulnerability-check
    parent: tox-py312
    voting: false
    timeout: 600
    nodeset: ubuntu-noble
    vars:
      tox_envlist:  airflow_safety
      bindep_profile: test py312

- job:
    name: airship-shipyard-dependency-vulnerability-check
    parent: tox-py312
    voting: false
    timeout: 600
    nodeset: ubuntu-noble
    vars:
      tox_envlist: shipyard_safety
      bindep_profile: test py312

- job:
    name: airship-shipyard-openstack-tox-pep8-noble
    parent: openstack-tox-pep8
    description: Runs pep8 job on noble
    nodeset: airship-shipyard-single-node-noble

- job:
    name: airship-shipyard-openstack-tox-cover-noble
    parent: openstack-tox-cover
    description: Runs cover job on noble
    nodeset: airship-shipyard-single-node-noble

- job:
    name: airship-shipyard-airflow-integration-test
    parent: tox-py312
    voting: true
    timeout: 3600
    nodeset: ubuntu-noble
    pre-run: tools/gate/playbooks/install-docker.yaml
    vars:
      tox_envlist: airflow_integration
      bindep_profile: test py312

- job:
    name: airship-shipyard-chart-build-gate
    description: Build charts using pinned Helm toolkit.
    timeout: 900
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-shipyard-single-node-noble
    vars:
      HTK_COMMIT: 49c117443391cec75e0bd52bb4a9d033325927ad

- job:
    name: airship-shipyard-chart-build-latest-htk
    description: Build charts using latest Helm toolkit.
    timeout: 900
    voting: false
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-shipyard-single-node-noble
    vars:
      HTK_COMMIT: master

- job:
    name: airship-shipyard-whitespace-lint-gate
    description: |
      Lints all files by checking them for whitespace.
    run: tools/gate/playbooks/zuul-linter.yaml
    nodeset: airship-shipyard-single-node-noble


- job:
    name: airship-shipyard-image-gate-ubuntu_noble
    description: |
      Job for running airship-shipyard image related jobs.
    timeout: 3600
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-shipyard-single-node-noble
    irrelevant-files: &irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      publish: false
      distro: ubuntu_noble
      tags:
        dynamic:
          patch_set: true

- job:
    name: shipyard-airskiff-deployment-noble-kubeadm
    description: |
      Deploy Memcached using Airskiff and submitted Shipyard changes.
    parent: treasuremap-airskiff-infra-deploy-base
    nodeset: treasuremap-airskiff-1node-ubuntu_noble
    required-projects:
      - name: airship/treasuremap
        override-checkout: v1.9
    vars:
      CLONE_SHIPYARD: false
      MAKE_SHIPYARD_IMAGES: true
      USE_ARMADA_GO: true
      DISTRO: ubuntu_noble
      DOCKER_REGISTRY: localhost:5000
      gate_scripts_relative_path: ../../airship/treasuremap

- job:
    name: airship-shipyard-docker-build-publish-ubuntu_noble
    description: |
      Job for publishing airship-shipyard images.
    timeout: 3600
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-shipyard-single-node-noble
    irrelevant-files: *irrelevant-files
    secrets:
      - airship_shipyard_quay_creds_2026
    vars:
      publish: true
      distro: ubuntu_noble
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest
          - airflow_3.1.5

- secret:
    name: airship_shipyard_quay_creds_2026
    data:
      username: !encrypted/pkcs1-oaep
        - C5ZM5bCcxhTZy82O/PcEgpFb5Q2aebhdaYJmcyIvbh2JK1HrLhyvik0qBprxfb97+aGGL
          z61j5CqEnXYh3ZxLk6w6NKcj32UZatdK2Vz7/2U/IxwAR9Iv+SiCVQzlGF+5RP0lFuYom
          hd9OWJW72BZ7ifH/tLC3lIckAJQBWYkfwu27WGvJ+Q10TAL3D9c+8QpDrgJL6EFULlsSM
          HKTgpu8E68KYGOl2mLRpEmkewmkf/d2XXC9tk1lqPWiwLJIatsxa+9ZCVYW/KzmHmMjt7
          fSgHoS2KBJvMefFpGmNkKsocM4MralgTiKIMUN3y69DpNt2C5HHpYY+travvwU/SLX0OC
          8E9seAIM+VHscUpJWihg0ecMf34gBXI4/eErN0i3UZZr/s2cKxstYgbye06kMuBRWI3y2
          AccbJt0TgCpilPw2hWlVuInAnwj8RZe3OKLs2vECWAMjbDcuGnD6C36uiQiihyE9dc+8c
          9KrR4PBXgyr15c6tSC/M3QwGeL05QtmmkzyjW3FpJiPTiKxWKEG7dQkNdQss9A83Kt9dN
          CevmCFIOwODYz/0e1GVEo1ptneOKD3OvArzCZ0Dn+hCWEb0Uu4LMCycVeQrbMt89oliju
          Q96ZbT/tWSKd4kDtPmAJR/rc8HYRvtxxJFdqW3w70NrRrcg7gzCnrBf1boHao4=
      password: !encrypted/pkcs1-oaep
        - AvoOA9AZ4oNm/5wjSqgFW0mO0cfTIt6AAMQQ2eEFT9BergG2+LHMEXRlmszZIxr3r5pQl
          X3SLtdX8W2DrBYpNU3K5irHlFvBkUlivVRg+VG6IHlariZW6/XVQtadA1dGFPHLaPz4aJ
          ep/VZ8GwsLI1QX9fZc0B9W4LxTAvYUcZbQtK7U67t3pDg8zvYiCHr42lHT3aGAjvS07wz
          o8bLVXYSlDdV+3Lo0aziSmH9IZZfymzazJf3fM8Hj7fJxLEAKKRfEtI5I1g+3cA9JByOh
          I7pJOFwIPUGIieMC1RrsZvKX0FPN2h2OF2A0nhaVRDOn0OHaTUT8kXm/9UuVr4RKbuC9o
          reBvi5wLrq4T9rci/cF5b1NnIwUqPi6jRTrTcWWKl3S65LO6w4BIObk8ACsvnIo1juWJz
          3TykrsoTtcoz0xCoZuRsxwnAYNzNK8WXIGjdvLd1a7B7WtZN0+8l8pC+L8XlchZT0UXxz
          wfNZM7uELfGNwrb63I14hqjERW/1M+pg/3Z8tAZqqupwels3tVdt+fPUJtXptC/RHDCAt
          R46U2EllKfRluIts3dSQucXlsrtwERM+vM66KQQ3bbvgsl24wQeg4zcmkUEcftepo8L2T
          TTR06S0mgZ5Gi5TfAikZbY7UEJu53UBPRnPA+xakxrUfiDj17XHp5nqcJvB2XE=

- job:
    name: shipyard-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/shipyard to airshipit/shipyard
    vars:
      git_mirror_repository: airshipit/shipyard
    secrets:
      - name: git_mirror_credentials
        secret: shipyard-airshipit-github-ed25519-secret-2026-01-13
        pass-to-parent: true

- secret:
    name: shipyard-airshipit-github-ed25519-secret-2026-01-13
    data:
      user: git
      host: github.com
      host_key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      ssh_key: !encrypted/pkcs1-oaep
        - FJB8S9Uj9c/Ong/Re7xM+e10225OWv/wjUOD10ROjmH898GfZkc7RPNNyGOV+dLs7/i02
          AnXYuAhCmnmnAXDZjRfbuYY6Bk6P3EC5Xll/BgAHLIRRG1qe0/aYg7smMuVUNs3RlHah0
          DsMn8ZUpqgUnwgVD1Fm4y4A3d70Q5n7PEjOWcBkG9BePALcStjcWkayjv1RetOyZuKl8d
          WdraD6eTDaytq3TvnbxRyImBcWe7t8w6ni0fb1JMIwDqK6nqrUrQp5SugOAcv8SalHCkf
          5hrQbGc5x0vLifsMMVjxxXiDdMM+C3HQZFRneIM6JAo0tcBKEmTVF51f/YEt5C9BCkxOs
          HUm19eC0JWWSOwsJkDujliWGmVM2fdwBQwx3JlR0rNbs4rU4nq1A+74NbJnmJZeK6ijZi
          aErg7goFdh+xT9weB3XRYSJaNhHl3S0O/A02UB02SC2kY9ohFJh17YMl958HzLFT4R8Gf
          MybRU8ydta6nH1aGZBdKzHDbPXL0xglI+KQVTUbDNOIr0wUkCuyMEOax+RAqOUqM+0Y7H
          Nyd7x3fKiFApZ5NBtiXphSAAUhkjblXTYr53okEhnyux2E3KikUtRhHUP2S1CiSfKe83D
          dFSv4HYcA05mcV6PactnsMb4Nki2abCo0ft1NpzHe5+2pYNXWpuom0II8Zx0x0=
