# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - docs-on-readthedocs
      - openstack-python35-jobs
      - openstack-python36-jobs
    vars:
      rtd_webhook_id: '38576'
    check:
      jobs:
        - openstack-tox-pep8
        - airship-shipyard-chart-build-gate
        - airship-shipyard-chart-build-latest-htk
        - airship-shipyard-whitespace-lint-gate
        - airship-shipyard-image-gate
    gate:
      jobs:
        - openstack-tox-pep8
        - airship-shipyard-chart-build-gate
        - airship-shipyard-whitespace-lint-gate
        - airship-shipyard-image-gate
    post:
      jobs:
        - airship-shipyard-docker-build-post

- nodeset:
    name: airship-shipyard-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: airship-shipyard-chart-build-gate
    description: Build charts using pinned Helm toolkit.
    timeout: 900
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-shipyard-single-node

- job:
    name: airship-shipyard-chart-build-latest-htk
    description: Build charts using latest Helm toolkit.
    timeout: 900
    voting: false
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-shipyard-single-node
    vars:
      HTK_COMMIT: master

- job:
    name: airship-shipyard-whitespace-lint-gate
    description: |
      Lints all files by checking them for whitespace.
    run: tools/gate/playbooks/zuul-linter.yaml
    nodeset: airship-shipyard-single-node

- job:
    name: airship-shipyard-image-base
    description: |
      Base job for running airship-shipyard image related jobs.
    timeout: 3600
    run: tools/gate/playbooks/run-image.yaml
    nodeset: airship-shipyard-single-node
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: airship-shipyard-image-gate
    description: |
      Run shipyard-image build.
    parent: airship-shipyard-image-base
    vars:
      publish: false
      tags:
        dynamic:
          patch_set: true

- job:
    name: airship-shipyard-docker-build-post
    timeout: 1800
    run: tools/gate/playbooks/run-image.yaml
    nodeset: airship-shipyard-single-node
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    secrets:
      - airship_shipyard_quay_creds
    vars:
      publish: true
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- secret:
    name: airship_shipyard_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - WD32oSzxpBLxbP0pm+JrO9/s08+anI7ntQyGcIFHXfdzR/aJy3N8n47CGi/L2VQgSNXcx
          kM5FdaO0otGCmLfjQHM4vyamD7AIDEgS7hCgY2p+Ew0spslYCGlNFYtlKLHLED2s7WV2a
          KA9AJPtXwNr2ogyRNsLx4Q1ALe5JdeOQBtn/tFHAj/t1azK8aiBLelbdFyzY+7omrdUd5
          ZxUKFg9dx+LR06Zf6cALuyoyD+WJFEVFE3GlUs6WDIln64j6PLBP2eqtkCloQFaxq+bMW
          EJnpdIUfrcQa2+S9qZ3T6KvS1xzEerw7FyIfWY3X12mv8xLkMEQMb8RW76NVVtfMHJAQr
          eP+nyLKRjsCaQ4B6siNmNsxgezmpc83WqtZ8mtMcsYXECqSqu5lkXgyeEQMtMNlBXBBeS
          OjB9ONx8dEV+f8V0olVCyA/K2BLm1I07jxhlTnKLkLpj5gb0xmtZyM/OfLK6i180n9ylN
          BXeHSJY2wGADZChYKVl1/DFn2w5R8sjf+JMUhDkfNUXFFfLS12lWexNH7V2PAy3mQrnQ0
          +IYNI959TAdyUwa9ZyQyu0lTkQpsuUwBSfnJ9+1orwlruzGeCeofIfHIzWitmB5yxtI/Z
          XRw2Uif34GEkerIQGnoQazOTVf6jAw/gp9X49+WpghTC+ExKTqCelggcKBukZA=
      password: !encrypted/pkcs1-oaep
        - ts6uhbQxb9EKWfQ1RmZUZGKoGEkJ9RkyupmmFHZllo2iEqNG21jrqhBbHVEt9iXqOGAUL
          AICzGos4p/RQXgISmmGVmBfR2MhH93txPLtKfIQCMw/838Mmy4z1gr1ALhepnEsgb3d9X
          fuWzbe0vBqHoXtBFlDXt3mUJq0yrOe+yQO0Ksb35wMz6pFdVY/USWGaLeBlO+JkA3Vk5E
          Wcse8OVZrPNYkY7mzObwqFx5F8vI/k6Cq334o3FlM+bRmV95TB/7fhmGgtpIQniJYA+dl
          TEOzukElwTlya+7xRIVlDyDUrjZUVo3nCzNV3ETf/O34fRKJqmWGsLGoTn/wVm/xuFAHm
          0m3DADRY1VI9hwNFXjErJm1cDV5kU8MVnSdTRWpjq72RZE8nGGtenlbdhyTvxdOdJ+IlX
          UWzz2pdilJzNNbDAhfRQ5ZkBUUKbWq47kUDKNWrg/uT70rfJ12HhCXgUTR2omHS9/P3OY
          J99B44mwMsfGXG5Oy7QUzidgfZKWdb9kGUOXz1z1FR5EpOF7w8N0A8tNcyqa6R4MnbRD4
          oaIgbDOWnXUd1A3Z6F/YlHu0/1J48xPZoZDjbsSGO3CMehZm26JdVVlc+s6MIleNhitBW
          PR1iMwRomxTw9ckoXexQ5Oz8EO73DPDIQO3r3iHVx4z4A/0iy8+mHoMxWyXiEo=
