---
schema: 'deckhand/DataSchema/v1'
metadata:
  schema: metadata/Control/v1
  name: shipyard/DeploymentConfiguration/v1
  labels:
    application: shipyard
data:
  $schema: 'http://json-schema.org/schema#'
  id: 'https://github.com/att-comdev/shipyard/deploymentConfiguration.yaml'
  type: 'object'
  properties:
    physical_provisioner:
      type: 'object'
      properties:
        deployment_strategy:
          type: 'string'
        deploy_interval:
          type: 'integer'
        deploy_timeout:
          type: 'integer'
        destroy_interval:
          type: 'integer'
        destroy_timeout:
          type: 'integer'
        join_wait:
          type: 'integer'
        prepare_node_interval:
          type: 'integer'
        prepare_node_timeout:
          type: 'integer'
        prepare_site_interval:
          type: 'integer'
        prepare_site_timeout:
          type: 'integer'
        verify_interval:
          type: 'integer'
        verify_timeout:
          type: 'integer'
      additionalProperties: false
    kubernetes:
      type: 'object'
      properties:
        node_status_interval:
          type: 'integer'
        node_status_timeout:
          type: 'integer'
      additionalProperties: false
    kubernetes_provisioner:
      type: 'object'
      properties:
        drain_timeout:
          type: 'integer'
        drain_grace_period:
          type: 'integer'
        clear_labels_timeout:
          type: 'integer'
        remove_etcd_timeout:
          type: 'integer'
        etcd_ready_timeout:
          type: 'integer'
      additionalProperties: false
    armada:
      type: 'object'
      properties:
        get_releases_timeout:
          type: 'integer'
        get_status_timeout:
          type: 'integer'
        manifest:
          type: 'string'
        post_apply_timeout:
          type: 'integer'
        validate_design_timeout:
          type: 'integer'
      additionalProperties: false
      required:
        - manifest
  additionalProperties: false
  required:
    - armada
