{{/*
Copyright (c) 2019 AT&T Intellectual Property. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.job_shipyard_db_auxiliary }}
{{- $envAll := . }}
{{- $mounts_shipyard_db_auxiliary := .Values.pod.mounts.shipyard_db_auxiliary.shipyard_db_auxiliary }}
{{- $mounts_shipyard_db_auxiliary_init := .Values.pod.mounts.shipyard_db_auxiliary.init_container }}
{{- $serviceAccountName := "shipyard-db-auxiliary" }}
{{ tuple $envAll "shipyard_db_auxiliary" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipyard-db-auxiliary
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "shipyard" "db-auxiliary" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
{{ dict "envAll" $envAll "podName" "shipyard-db-auxiliary" "containerNames" (list "init" "shipyard-db-auxiliary") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-shipyard-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-shipyard-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
{{ dict "envAll" $envAll "application" "db_auxiliary" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      serviceAccountName: {{ $serviceAccountName }}
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
      initContainers:
{{ tuple $envAll "shipyard_db_auxiliary" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: shipyard-db-auxiliary
          image: {{ .Values.images.tags.shipyard_db_auxiliary | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.shipyard_db_auxiliary | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "db_auxiliary" "container" "shipyard_db_auxiliary" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_shipyard_db.user }}
                  key: SHIPYARD_DATABASE_HOST
            - name: USER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_shipyard_db.user }}
                  key: SHIPYARD_DATABASE_NAME
            - name: USER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_shipyard_db.user }}
                  key: SHIPYARD_DATABASE_USERNAME
            - name: DB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_shipyard_db.admin }}
                  key: SHIPYARD_DATABASE_USERNAME
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_shipyard_db.admin }}
                  key: SHIPYARD_DATABASE_PASSWORD
            - name: AIRFLOW_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_airflow_db.user }}
                  key: AIRFLOW_DATABASE_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.postgresql_shipyard_db.user }}
                  key: DATABASE_PORT
            - name: SHIPYARD_AUXILIARY_CONFIG
              value: "True"
          command:
            - /tmp/shipyard-db-auxiliary.sh
          volumeMounts:
            - name: shipyard-bin
              mountPath: /tmp/shipyard-db-auxiliary.sh
              subPath: shipyard-db-auxiliary.sh
              readOnly: true
{{ if $mounts_shipyard_db_auxiliary.volumeMounts }}{{ toYaml $mounts_shipyard_db_auxiliary.volumeMounts | indent 10 }}{{ end }}
      volumes:
        - name: shipyard-bin
          configMap:
            name: shipyard-bin
            defaultMode: 0555
{{ if $mounts_shipyard_db_auxiliary.volumes }}{{ toYaml $mounts_shipyard_db_auxiliary.volumes | indent 6 }}{{ end }}
{{- end }}
